const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  UPDATE_CART_TO_FIREBASE: 'UPDATE_CART_TO_FIREBASE',
  GET_CART_FROM_FIREBASE: 'GET_CART_FROM_FIREBASE'
}


export default CartActionTypes;